# coding: utf-8
import boto3
session = boto3.Session('ec2')
session = boto3.Session(profile_name = 'pythonAutomation')
ec2 = session.resource('ec2')
as_client = boto3.client('autoscaling')
as_client = session.client('autoscaling')
as_client.describe_auto_scaling_groups()
as_client.describe_policies()
as_client.execute_policy('AutoScalingGroupName': 'Notifon Group','PolicyName': 'Scale Up')
as_client.execute_policy(AutoScalingGroupName='Notifon Group',PolicyName='Scale Up')
as_client.execute_policy(AutoScalingGroupName='Notifon Group',PolicyName='Scale Down')
as_client.execute_policy(AutoScalingGroupName='Notifon Group',PolicyName='Scale Up')
as_client.execute_policy(AutoScalingGroupName='Notifon Group',PolicyName='Scale Down')
get_ipython().run_line_magic('history', '')
get_ipython().run_line_magic('save', 'autoscale_example.py 1-15')
